# Generated by Django 4.1.5 on 2023-02-20 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aqua",
        ),
    ]
