# Generated by Django 4.1.5 on 2023-02-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_homenavimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='light',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='rfid',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stairs',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sunblind',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Aqua',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Light',
        ),
        migrations.DeleteModel(
            name='Rfid',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Stairs',
        ),
        migrations.DeleteModel(
            name='Sunblind',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
