# Generated by Django 4.1.5 on 2023-03-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_alter_temp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temp",
            name="humi",
            field=models.FloatField(default=""),
        ),
        migrations.AlterField(
            model_name="temp",
            name="temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="temp",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
