# Generated by Django 4.1.5 on 2023-03-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_alter_temp_humi_alter_temp_temp_alter_temp_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fun", models.CharField(default="", max_length=100)),
                ("message", models.CharField(default="", max_length=100)),
                ("answer", models.CharField(default="", max_length=100)),
                ("port", models.IntegerField()),
            ],
        ),
    ]
