# Generated by Django 4.1.5 on 2023-02-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngrok',
            name='ngrok',
            field=models.URLField(default=''),
        ),
    ]
