# Generated by Django 4.1.5 on 2023-02-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeNavImage',
        ),
    ]
