# Generated by Django 4.1.1 on 2023-01-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_homenavimage_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenavimage',
            name='light',
            field=models.ImageField(default='lamp.png', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='homenavimage',
            name='logout',
            field=models.ImageField(default='logout.png', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='homenavimage',
            name='profile',
            field=models.ImageField(default='user.png', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='homenavimage',
            name='sensor',
            field=models.ImageField(default='connect.png', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='homenavimage',
            name='stairs',
            field=models.ImageField(default='stairs.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
