# Generated by Django 4.1.5 on 2023-02-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='r255g255b255', max_length=100)),
                ('led_start', models.CharField(default='00:00:00', max_length=10)),
                ('led_stop', models.CharField(default='00:00:00', max_length=10)),
                ('fluo_start', models.CharField(default='00:00:00', max_length=10)),
                ('fluo_stop', models.CharField(default='00:00:00', max_length=10)),
                ('mode', models.BooleanField(default=False)),
                ('led_mode', models.BooleanField(default=False)),
                ('fluo_mode', models.BooleanField(default=False)),
                ('aquarium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
