# Generated by Django 4.1.5 on 2023-02-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fun', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aqua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='r255g255b255', max_length=100)),
                ('led_start', models.CharField(default='00:00:00', max_length=10)),
                ('led_stop', models.CharField(default='00:00:00', max_length=10)),
                ('fluo_start', models.CharField(default='00:00:00', max_length=10)),
                ('fluo_stop', models.CharField(default='00:00:00', max_length=10)),
                ('mode', models.BooleanField(default=False)),
                ('led_mode', models.BooleanField(default=False)),
                ('fluo_mode', models.BooleanField(default=False)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aquarium.device')),
            ],
        ),
    ]
