# Generated by Django 4.1.5 on 2023-02-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aqua',
            old_name='sensor',
            new_name='device',
        ),
    ]
