# Generated by Django 4.1.1 on 2022-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sensor_fun_alter_sensor_id_temp_sunblind_stairs_rfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqua',
            name='fluo_start',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aqua',
            name='fluo_stop',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aqua',
            name='led_start',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aqua',
            name='led_stop',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aqua',
            name='mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
