# Generated by Django 4.1.1 on 2023-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_homenavimage_light_homenavimage_logout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homenavimage',
            name='avatar',
        ),
        migrations.AddField(
            model_name='homenavimage',
            name='home',
            field=models.ImageField(default='static/images/home.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='aquarium',
            field=models.ImageField(default='static/images/aqua.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='light',
            field=models.ImageField(default='static/images/lamp.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='logout',
            field=models.ImageField(default='static/images/logout.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='profile',
            field=models.ImageField(default='static/images/user.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='rpl',
            field=models.ImageField(default='static/images/rfid.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='sensor',
            field=models.ImageField(default='static/images/connect.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='stairs',
            field=models.ImageField(default='static/images/stairs.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='sunblind',
            field=models.ImageField(default='static/images/sunblind.png', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='homenavimage',
            name='temperature',
            field=models.ImageField(default='static/images/temp.png', upload_to='static/images'),
        ),
    ]
