# Generated by Django 4.1.1 on 2022-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aqua_fluo_mode_aqua_led_mode_alter_aqua_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqua',
            name='fluo_start',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='aqua',
            name='fluo_stop',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='aqua',
            name='led_start',
            field=models.TimeField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='aqua',
            name='led_stop',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='temp',
            name='humi',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
