# Generated by Django 4.1.1 on 2022-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_aqua_fluo_start_alter_aqua_fluo_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='name',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stairs',
            name='brightness',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='stairs',
            name='lightTime',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='stairs',
            name='steps',
            field=models.IntegerField(default=30),
        ),
    ]
