# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rfid_name_alter_rfid_uid_alter_stairs_brightness_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lamp',
            new_name='Light',
        ),
        migrations.AlterField(
            model_name='rfid',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
