# Generated by Django 4.1.1 on 2022-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_lamp_light_alter_rfid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stairs',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
