# Generated by Django 4.1.1 on 2022-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stairs_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('lamp', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rfid',
            name='light',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stairs',
            name='steps',
            field=models.IntegerField(default=200),
        ),
    ]
