# Generated by Django 4.1.1 on 2022-10-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_button_rfid_light_alter_stairs_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='name',
        ),
        migrations.AddField(
            model_name='button',
            name='sensor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.sensor'),
            preserve_default=False,
        ),
    ]
