# Generated by Django 4.1.1 on 2022-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_button_name_button_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='lamp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
