# Generated by Django 4.1.1 on 2022-10-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rfid_lamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='light',
        ),
        migrations.RemoveField(
            model_name='rfid',
            name='name',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('uid', models.IntegerField(default=0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor')),
            ],
        ),
    ]
