# Generated by Django 4.1.1 on 2022-10-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_rfid_light_remove_rfid_name_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='uid',
        ),
    ]
