# Generated by Django 4.1.1 on 2022-11-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_remove_rfid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aqua',
            name='led_start',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
